drop function SelectGiay
drop function SelectPT

drop proc showGiay
drop proc showPT
drop proc showMaSPByNH
drop proc showNH
drop proc showMaDMByNH
drop proc addGiay
drop proc addPT
drop proc showLPT
drop proc AnhSP
drop proc up_Giay
drop proc up_PT
drop proc up_TimKiemGiay
drop proc up_TimKiemPT
drop proc up_CTGiay
drop proc up_CTPT
drop proc usp_delete_sp
drop proc usp_delete_hoadon
drop proc showCTHD
drop proc deleteCTHD
drop proc saveCTHD
drop proc showMaSP
drop proc showMaHD
drop proc showMaSize
drop proc showHD
drop proc saveHD
drop proc deleteHD
drop proc showMaKH
drop proc showMaGiamGia
drop proc showMaPTTT
drop proc showMaPTVC
drop proc showMGG
drop proc addMGG
drop proc saveMGG
drop proc deleteMGG
drop proc showUser
drop proc addUser
drop proc saveUser
drop proc deleteUser
drop proc showSize
drop proc updateSize
drop proc addSize
drop proc usp_delete_masize
drop proc showPTTT
drop proc addPTTT
drop proc savePTTT
drop proc deletePTTT
drop proc showPTVC
drop proc addPTVC
drop proc savePTVC
drop proc deletePTVC
drop proc Thongketheonam
drop proc TongDoanhThuMoiNam
drop proc Thongkehientai
drop proc selectNam
drop proc usp_update_sp_size
drop proc showSPSize